### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [ogix/ng2-fancy-image-uploader#13]
I am getting the following error while  run the **ng serve**

ERROR in Error: Metadata version mismatch for module D:/Project_Santhosh/Reactive FormsExample/node_modules/ng2-fancy-image-uploader/dist/index.d.ts, found version 4, expected 3, resolving symbol AppModule in D:/Project_Santhosh/Reactive FormsExample/src/app/app.module.ts, resolving symbol AppModule in D:/Project_Santhosh/Reactive FormsExample/src/app/app.module.ts

**Comment by ogix** [comment]
What angular version are you using?
