### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by guoguo13** [ogix/ng2-fancy-image-uploader#3]
Hello, It has a error when I run the project, I do not know how to solve, could you help me?

ERROR in D:/Project/node_modules/ng2-fancy-image-uploader/dist/src/fancy-im
age-uploader.component.d.ts (1,1): Cannot find type definition file for 'cropper
js'.

ERROR in Error encountered resolving symbol values statically. Calling function
'makeDecorator', function calls are not supported.

**Comment by ogix** [comment]
Should be fixed now
