### ISSUE TITLE
onUpload event not fired with autoUpload: false option

### ISSUE THREAD

**Issue by StickNitro** [ogix/ng2-fancy-image-uploader#4]
Hi,

I am trying to use this module (great module by the way), I want to be able to access the file and read the data url without uploading the file.

I found the autoUpload option which stops the upload but then the onUpload event does not file and ngModule is null

Can you advise how I can access the selected file?

**Comment by ogix** [comment]
Hello,
`onUpload `is triggered when actual upload happens.
There is another output `onStatusChange `which I guess is what you want. Then in your component you can check for status `Selected` and get data url from referenced `FancyImageUploaderComponent `object: 

```
@ViewChild(FancyImageUploaderComponent) imageUploader: FancyImageUploaderComponent;

imageUploaderStatusChanged(status: Status) {
  if (status === Status.Selected) {
    let dataUrl = imageUploader.imageThumbnail;
  }
}

```

I haven't tried this sample so not sure if that will work.

**Comment by maxpaynestory** [comment]
```
(onStatusChange)="imageUploaderStatusChanged($event)"
```

The above solution works.

**Comment by maxpaynestory** [comment]
Now the question arise how to invoke upload when autoUpload is false?

**Comment by ogix** [comment]
Declare a variable for the component and call upload():
```
<fancy-image-uploader
    #imageUploader
    [options]="options">
</fancy-image-uploader>

<button type="button" (click)="imageUploader.upload()">Upload</button>
```
