### ISSUE TITLE
Styles missing?

### ISSUE THREAD

**Issue by davidstankus** [ogix/ng2-fancy-image-uploader#5]
Hey there, So Im missing the error styles and Im not sure why.
![screen shot 2017-11-13 at 3 31 17 pm](https://user-images.githubusercontent.com/15986886/32750298-dc10854a-c887-11e7-9ee9-216405eebdb0.png)

Everything seems to be working fine, just missing the styles. The error styles in the demo look great and i'd love to use them. Any help would be appreciated.

Thanks!

**Comment by ogix** [comment]
Hello! Can you check if any of your styles override image uploader's styles using browser's developer tools?
