### ISSUE TITLE
BrowserModule has already been loaded (on lazy load module)

### ISSUE THREAD

**Issue by tobecwb** [ogix/ng2-fancy-image-uploader#7]
When I try to import FancyImageUploaderModule on a lazy module, I got the following error:

`Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

My main module (app.module.ts):

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    appRouter
  ],
  providers: [
  ],
  bootstrap: [AppComponent]
})
```

Lazy module with FancyImageUploaderModule:

```
@NgModule({
  imports: [
    CommonModule,
    PainelRouter,
    FancyImageUploaderModule
  ],
  declarations: [PainelComponent]
})
```

**Comment by ogix** [comment]
Thanks for reporting! I guess I use wrong module (BrowserModule). Will make a fix this evening.
