### ISSUE TITLE
BrowserModule was be imported

### ISSUE THREAD

**Issue by SuperDoudou** [ogix/ng2-fancy-image-uploader#8]
when i using lazy load, and put ng2-image-upload in a child module , appear BrowserModule has already been loaded Error. So I think this module import BrowserModule or BrowserAnimationsModule. But, only AppModule should import it.
I suggest import CommonModule rather than BrowserModule

**Comment by ogix** [comment]
This was fixed in the recent version. Please update to v2.0.1
