### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by rbarkhouse** [ogix/ng2-fancy-image-uploader#9]
This component looks great but I'm getting the following errors when trying to use ng2-fancy-image-uploader with Angular 4.3.2:

_WARNING in ./node_modules/ng2-fancy-image-uploader/node_modules/@angular/core/esm5/core.js
6586:15-36 Critical dependency: the request of a dependency is an expression
WARNING in ./node_modules/ng2-fancy-image-uploader/node_modules/@angular/core/esm5/core.js
6606:15-102 Critical dependency: the request of a dependency is an expression_

As the instructions indicated, I added FancyImageUploaderModule to the imports array of my AppModule -- is there another syntax that can be used to include this module?

This seems related to https://github.com/webpack/webpack/issues/2964 but I couldn't find any concrete resolution to that problem...

**Comment by ogix** [comment]
Hello, for 4.3.2 Angular version use image uploader version v1.6.1.
v2.0.0 and higher is for Angular 5.

**Comment by rbarkhouse** [comment]
Ok great, thanks for the info!

**Comment by Ianc22** [comment]
Having the same trouble with Angular 6... Any ideas how to fix this?
